### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by suriya110** [testmaan/homebrew-tm#9]
By default it takes only getByPlaceholder.

**Comment by lokeshgrootan** [comment]
Give more details

**Comment by lokeshgrootan** [comment]
Fixed in TM 1.0.15

**Comment by Yuviak** [comment]
<img width="1440" alt="Screenshot 2024-04-11 at 7 29 33 PM" src="https://github.com/testmanio/homebrew-tm/assets/121085168/08a7824e-d9d1-4f49-aa7c-a4efcf61ef57">
<img width="1440" alt="Screenshot 2024-04-11 at 7 30 18 PM" src="https://github.com/testmanio/homebrew-tm/assets/121085168/946f9ee1-184c-4ef7-8401-6c4be307f0cf">

Issue still exists 
Testman version 3.0.1
Steps:
Testman 
Select drag and drop in step type and select from by and to by provide none and click on generate
Playwirght getbyplaceholder is gets displayed so unable the run the case 

**Expected** 
getbyplaceholder replace locator means cases are getting automated

Refer the screenshot both Testman and Playwirght
